module.exports = [
  {
    id: "sharepoint-foundations",
    title: "SharePoint Online Foundations",
    category: "SharePoint",
    level: "Intermediate",
    duration: "3 hours",
    format: "Guide + checklist",
    detailPath: "/course-materials/sharepoint-online-foundations.md",
    videoUrl: "",
    documentUrl: "",
    pdfUrl: "",
    downloadName: "sharepoint-online-foundations.md",
    description: "Learn site architecture, document collaboration, permissions, and content lifecycle basics for SharePoint Online."
  },
  {
    id: "exchange-online-operations",
    title: "Exchange Online Operations",
    category: "Exchange Online",
    level: "Intermediate",
    duration: "2.5 hours",
    format: "Guide + lab notes",
    detailPath: "/course-materials/exchange-online-operations.md",
    videoUrl: "",
    documentUrl: "",
    pdfUrl: "",
    downloadName: "exchange-online-operations.md",
    description: "Cover mailbox administration, transport hygiene, retention, and common operational tasks in Exchange Online."
  },
  {
    id: "teams-admin-essentials",
    title: "Microsoft Teams Admin Essentials",
    category: "Teams",
    level: "Beginner",
    duration: "2 hours",
    format: "Playbook",
    detailPath: "/course-materials/teams-admin-essentials.md",
    videoUrl: "",
    documentUrl: "",
    pdfUrl: "",
    downloadName: "teams-admin-essentials.md",
    description: "Build a working foundation for Teams policies, meetings, app governance, and collaboration rollout."
  },
  {
    id: "entra-id-core-identity",
    title: "Microsoft Entra ID Core Identity",
    category: "Entra ID",
    level: "Advanced",
    duration: "3.5 hours",
    format: "Architecture guide",
    detailPath: "/course-materials/entra-id-core-identity.md",
    videoUrl: "",
    documentUrl: "",
    pdfUrl: "",
    downloadName: "entra-id-core-identity.md",
    description: "Understand tenants, authentication flows, application registrations, conditional access, and identity governance."
  },
  {
    id: "defender-xdr-essentials",
    title: "Microsoft Defender XDR Essentials",
    category: "Defender",
    level: "Advanced",
    duration: "4 hours",
    format: "Workbook",
    detailPath: "/course-materials/defender-xdr-essentials.md",
    videoUrl: "",
    documentUrl: "",
    pdfUrl: "",
    downloadName: "defender-xdr-essentials.md",
    description: "Review alert triage, endpoint and email protection, incident workflows, and defender operations baselines."
  },
  {
    id: "intune-device-management",
    title: "Intune Device Management",
    category: "Intune",
    level: "Intermediate",
    duration: "2 hours",
    format: "Starter pack",
    detailPath: "/course-materials/intune-device-management.md",
    videoUrl: "",
    documentUrl: "",
    pdfUrl: "",
    downloadName: "intune-device-management.md",
    description: "Practice enrollment, compliance, configuration profiles, app deployment, and endpoint management patterns."
  }
];